name: CI/CD - FastAPI AI Interview App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install ruff pytest

      - name: Lint with Ruff
        run: ruff check backend --fix

      - name: Run tests
        run: pytest backend/tests

      - name: Trigger Render Deployment
        run: curl -X POST $RENDER_DEPLOY_HOOK
